name: SLS Deploy
on:
    push:
        branches: [dev]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: dev
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux sharp
            - name: Serverless Deploy
              uses: vnshgrg/github-action-amazon-lambda-serverless@nodejs
              with:
                  args: deploy --stage dev
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  DB_URL: ${{ secrets.DB_URL }}
                  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
                  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
                  STRIPE_PK: ${{ secrets.STRIPE_PK }}
                  STRIPE_SK: ${{ secrets.STRIPE_SK }}
                  STRIPE_CONNECT_CLIENT_ID: ${{ secrets.STRIPE_CONNECT_CLIENT_ID }}
                  STRIPE_CONNECT_ACCOUNT_RETURN_URL: ${{ secrets.STRIPE_CONNECT_ACCOUNT_RETURN_URL }}
                  STRIPE_CONNECT_ACCOUNT_REFRESH_URL: ${{ secrets.STRIPE_CONNECT_ACCOUNT_REFRESH_URL }}
                  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
                  IP_STACK_KEY: ${{ secrets.IP_STACK_KEY }}
                  ALGOLIA_APP_ID: "${{ secrets.ALGOLIA_APP_ID }}"
                  ALGOLIA_ADMIN_API_KEY: "${{ secrets.ALGOLIA_ADMIN_API_KEY }}"
                  ALGOLIA_SEARCH_API_KEY: "${{ secrets.ALGOLIA_SEARCH_API_KEY }}"
                  FRONTEND_BASE_URL: "${{ secrets.FRONTEND_BASE_URL }}"
                  GOOGLE_MAP_API_KEY: "${{ secrets.GOOGLE_MAP_API_KEY }}"
                  PRISMA_TARGET: "rhel-openssl-1.0.x"
